package net.runelite.client.plugins.LXenSanfew;

public enum LXenSanfewState {
	UNHANDLED_STATE,
	TIMEOUT,
	MOVING,
	ITERATING,
	WITHDRAW_DUST,
	WITHDRAW_GRASS,
	WITHDRAW_NAILS,
	WITHDRAW_RESTORES,
	CLOSE_BANK,
	COMBINE_DUST,
	COMBINE_GRASS,
	COMBINE_NAILS,
	OPEN_BANK,
	DEPOSIT
}